Anonymous:
    description: I18N_OPENXPKI_CONFIG_AUTH_STACK_DESCRIPTION_ANONYMOUS</description>
    handler: Anonymous

User:
    description: I18N_OPENXPKI_CONFIG_AUTH_STACK_DESCRIPTION_USER
    handler: User Password

Operator:
    description: I18N_OPENXPKI_CONFIG_AUTH_STACK_DESCRIPTION_OPERATOR</description>
    handler: Operator Password

External Dynamic:
    description: I18N_OPENXPKI_CONFIG_AUTH_STACK_DESCRIPTION_EXTERNAL_DYNAMIC</description>
    handler: External Dynamic Role

External Static:
    description: I18N_OPENXPKI_CONFIG_AUTH_STACK_DESCRIPTION_EXTERNAL_STATIC</description>
    handler: External Static Role

Certificate Challenge/Response:
    description: I18N_OPENXPKI_CONFIG_AUTH_HANDLER_DESCRIPTION_CERTIFICATE</description>
    handler: Signature

Certificate via Webserver:
    description: I18N_OPENXPKI_CONFIG_AUTH_HANDLER_DESCRIPTION_CERTIFICATE_WEBSERVER</description>
    handler: Certificate

_System:
    description: I18N_OPENXPKI_CONFIG_AUTH_STACK_DESCRIPTION_AUTH_SYSTEM</description>
    handler: System


